AllCops:
  Exclude:
    - bin/*
    - config/unicorn.rb
    - db/**
    - db/migrate/*
    - vendor/**/*

Rails:
  Enabled: true

# Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

LineLength:
  Max: 100

MethodLength:
  Max: 20
