# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 724d8fc41e532e5b4d8570adf2519000ec65e3156375a0aa1098a20700f2ad1ff994dade75eac4c4e268d9fe5f2a92aad5e8142d3ef771be8f179a594cacf7ab

test:
  secret_key_base: f9c44698568738a5005422915e5952df8da27811e7c2db22d599678f76ae57c59ff984b823ee7a816a24eea65c13e3cc135d3989d9a407e71070acb942178921

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
